### ISSUE TITLE
Quartz 66.000MHz

### ISSUE THREAD

**Issue by luciust** [dh219/DSTB#1]
This could be either 3.3V or 5V version? What is your source?

**Comment by dh219** [comment]
Yes, the circuit board supports selecting 3V3 or 5V. Any 7x5mm oscillator up to 66MHz should work. I happened to have some in my parts bin, but I normally source from Farnell UK. They presently have 64MHz oscillators which would be fine. The CPU will run at OSC/4. The SDRAM controller cannot work beyond 66MHz. A 50MHz oscillator will work fine, but the CPU will run at 12.5MHz, therefore.

**Comment by luciust** [comment]
Thanks, found the 66MHz in correct package, appreciate the additional comments!
