### ISSUE TITLE
The Kicad project is missing the "david" and "SN74CB3T3245DW" libraries.

### ISSUE THREAD

**Issue by pi1541** [dh219/DSTB#2]
The schematic references;
david:68000D_PLUG
david:IS42S16320D-7TL
SN74CB3T3245DW:SN74CB3T3245DW

these are missing from the folder/project.
Therefore the schematic symbols are missing in the schematic view and appear as "??".

Perhaps export them to the local project.

![image](https://user-images.githubusercontent.com/39399323/166626863-41a01018-ea2f-4af1-ba7b-ed6e5f1a64b8.png)

**Comment by dh219** [comment]
Sorry, you're right. I need to refactor these projects to remove external dependencies.

In the short term, as a work around, the libraries are avalable in the DFB repository: https://github.com/dh219/DFB/tree/main/DFB1/kicad5/kicad-libraries

**Comment by dh219** [comment]
I believe this is now resolved. Thanks for the report.
